/* tslint:disable */
/* eslint-disable */
declare const canonical_abi_realloc: (a: number, b: number, c: number, d: number) => number;
declare const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
declare const intounderlyingsource_pull: (a: number, b: any) => any;
declare const intounderlyingsource_cancel: (a: number) => void;
declare const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
declare const intounderlyingbytesource_type: (a: number) => [number, number];
declare const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
declare const intounderlyingbytesource_start: (a: number, b: any) => void;
declare const intounderlyingbytesource_pull: (a: number, b: any) => any;
declare const intounderlyingbytesource_cancel: (a: number) => void;
declare const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
declare const intounderlyingsink_write: (a: number, b: any) => any;
declare const intounderlyingsink_close: (a: number) => any;
declare const intounderlyingsink_abort: (a: number, b: any) => any;
declare const __wbg_trap_free: (a: number, b: number) => void;
declare const directory___getClassname: (a: number) => [number, number];
declare const __wbg_directory_free: (a: number, b: number) => void;
declare const directory_new: (a: number) => [number, number, number];
declare const directory_readDir: (a: number, b: number, c: number) => any;
declare const directory_writeFile: (a: number, b: number, c: number, d: any) => any;
declare const directory_readFile: (a: number, b: number, c: number) => any;
declare const directory_readTextFile: (a: number, b: number, c: number) => any;
declare const directory_createDir: (a: number, b: number, c: number) => any;
declare const directory_removeDir: (a: number, b: number, c: number) => any;
declare const directory_removeFile: (a: number, b: number, c: number) => any;
declare const __wbg_wasmerpackage_free: (a: number, b: number) => void;
declare const __wbg_set_wasmerpackage_manifest: (a: number, b: any) => void;
declare const __wbg_get_wasmerpackage_data: (a: number) => [number, number];
declare const __wbg_atom_free: (a: number, b: number) => void;
declare const __wbg_publishpackageoutput_free: (a: number, b: number) => void;
declare const __wbg_get_publishpackageoutput_manifest: (a: number) => any;
declare const __wbg_set_publishpackageoutput_manifest: (a: number, b: any) => void;
declare const __wbg_get_publishpackageoutput_hash: (a: number) => [number, number];
declare const wasmer_createPackage: (a: any) => any;
declare const wasmer_publishPackage: (a: number) => any;
declare const runWasix: (a: any, b: any) => any;
declare const wat2wasm: (a: number, b: number) => [number, number, number];
declare const on_start: () => void;
declare const setSDKUrl: (a: any) => void;
declare const setWorkerUrl: (a: any) => void;
declare const initializeLogger: (a: number, b: number) => [number, number];
declare const __wbg_instance_free: (a: number, b: number) => void;
declare const __wbg_get_instance_stdin: (a: number) => any;
declare const __wbg_get_instance_stdout: (a: number) => any;
declare const __wbg_get_instance_stderr: (a: number) => any;
declare const instance_wait: (a: number) => any;
declare const __wbg_deployedapp_free: (a: number, b: number) => void;
declare const __wbg_get_deployedapp_id: (a: number) => [number, number];
declare const __wbg_set_deployedapp_id: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_created_at: (a: number) => [number, number];
declare const __wbg_set_deployedapp_created_at: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_version: (a: number) => [number, number];
declare const __wbg_set_deployedapp_version: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_description: (a: number) => [number, number];
declare const __wbg_set_deployedapp_description: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_yaml_config: (a: number) => [number, number];
declare const __wbg_set_deployedapp_yaml_config: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_user_yaml_config: (a: number) => [number, number];
declare const __wbg_set_deployedapp_user_yaml_config: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_config: (a: number) => [number, number];
declare const __wbg_set_deployedapp_config: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_json_config: (a: number) => [number, number];
declare const __wbg_set_deployedapp_json_config: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_url: (a: number) => [number, number];
declare const __wbg_set_deployedapp_url: (a: number, b: number, c: number) => void;
declare const __wbg_get_deployedapp_app_id: (a: number) => [number, number];
declare const __wbg_set_deployedapp_app_id: (a: number, b: number, c: number) => void;
declare const wasmer_deployApp: (a: any) => any;
declare const wasmer_deleteApp: (a: any) => any;
declare const runtime___getClassname: (a: number) => [number, number];
declare const __wbg_runtime_free: (a: number, b: number) => void;
declare const runtime_js_new: (a: number) => [number, number, number];
declare const runtime_global: (a: number) => [number, number, number];
declare const __wbg_user_free: (a: number, b: number) => void;
declare const wasmer_whoami: () => any;
declare const writablestreamsink_close: (a: number) => any;
declare const writablestreamsink_abort: (a: number, b: any) => void;
declare const writablestreamsink_write: (a: number, b: any) => any;
declare const __wbg_readablestreamsource_free: (a: number, b: number) => void;
declare const readablestreamsource_pull: (a: number, b: any) => any;
declare const readablestreamsource_cancel: (a: number) => void;
declare const readablestreamsource_type: (a: number) => any;
declare const wasmer___getClassname: (a: number) => [number, number];
declare const __wbg_wasmer_free: (a: number, b: number) => void;
declare const __wbg_get_wasmer_entrypoint: (a: number) => number;
declare const __wbg_set_wasmer_entrypoint: (a: number, b: number) => void;
declare const __wbg_get_wasmer_commands: (a: number) => any;
declare const __wbg_set_wasmer_commands: (a: number, b: any) => void;
declare const __wbg_get_wasmer_pkg: (a: number) => number;
declare const __wbg_set_wasmer_pkg: (a: number, b: number) => void;
declare const userpackagedefinition___getClassname: (a: number) => [number, number];
declare const __wbg_userpackagedefinition_free: (a: number, b: number) => void;
declare const __wbg_get_userpackagedefinition_hash: (a: number) => [number, number];
declare const __wbg_set_userpackagedefinition_hash: (a: number, b: number, c: number) => void;
declare const wasmer_fromRegistry: (a: number, b: number, c: number) => any;
declare const wasmer_fromFile: (a: any, b: number) => any;
declare const wasmer_fromWasm: (a: any, b: number) => [number, number, number];
declare const __wbg_command_free: (a: number, b: number) => void;
declare const __wbg_get_command_name: (a: number) => any;
declare const __wbg_set_command_name: (a: number, b: any) => void;
declare const command_rename: (a: number, b: any) => void;
declare const command_run: (a: number, b: number) => any;
declare const command_binary: (a: number) => any;
declare const __wbg_threadpoolworker_free: (a: number, b: number) => void;
declare const threadpoolworker_new: (a: number) => number;
declare const threadpoolworker_handle: (a: number, b: any) => any;
declare const __wbg_set_wasmerpackage_data: (a: number, b: number, c: number) => void;
declare const __wbg_get_wasmerpackage_manifest: (a: number) => any;
declare const canonical_abi_free: (a: number, b: number, c: number) => void;
declare const trap___wbg_wasmer_trap: () => void;
declare const __wbg_set_user_username: (a: number, b: number, c: number) => void;
declare const __wbg_volume_free: (a: number, b: number) => void;
declare const __wbg_get_user_username: (a: number) => [number, number];
declare const __wbg_set_publishpackageoutput_hash: (a: number, b: number, c: number) => void;
declare const __wbg_get_user_id: (a: number) => [number, number];
declare const __wbg_writablestreamsink_free: (a: number, b: number) => void;
declare const __wbg_set_user_id: (a: number, b: number, c: number) => void;
declare const memory: WebAssembly.Memory;
declare const __wbindgen_malloc: (a: number, b: number) => number;
declare const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
declare const __wbindgen_exn_store: (a: number) => void;
declare const __externref_table_alloc: () => number;
declare const __wbindgen_export_5: WebAssembly.Table;
declare const __wbindgen_export_6: WebAssembly.Table;
declare const __externref_table_dealloc: (a: number) => void;
declare const closure544_externref_shim: (a: number, b: number, c: any) => void;
declare const closure806_externref_shim: (a: number, b: number) => any;
declare const closure807_externref_shim: (a: number, b: number, c: any) => number;
declare const closure1343_externref_shim_multivalue_shim: (a: number, b: number, c: any) => [number, number];
declare const closure1345_externref_shim_multivalue_shim: (a: number, b: number, c: any) => [number, number, number];
declare const closure191_externref_shim: (a: number, b: number, c: any, d: any) => void;
declare const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
declare const __wbindgen_start: (a: number) => void;

declare const wasm_bytes___externref_table_alloc: typeof __externref_table_alloc;
declare const wasm_bytes___externref_table_dealloc: typeof __externref_table_dealloc;
declare const wasm_bytes___wbg_atom_free: typeof __wbg_atom_free;
declare const wasm_bytes___wbg_command_free: typeof __wbg_command_free;
declare const wasm_bytes___wbg_deployedapp_free: typeof __wbg_deployedapp_free;
declare const wasm_bytes___wbg_directory_free: typeof __wbg_directory_free;
declare const wasm_bytes___wbg_get_command_name: typeof __wbg_get_command_name;
declare const wasm_bytes___wbg_get_deployedapp_app_id: typeof __wbg_get_deployedapp_app_id;
declare const wasm_bytes___wbg_get_deployedapp_config: typeof __wbg_get_deployedapp_config;
declare const wasm_bytes___wbg_get_deployedapp_created_at: typeof __wbg_get_deployedapp_created_at;
declare const wasm_bytes___wbg_get_deployedapp_description: typeof __wbg_get_deployedapp_description;
declare const wasm_bytes___wbg_get_deployedapp_id: typeof __wbg_get_deployedapp_id;
declare const wasm_bytes___wbg_get_deployedapp_json_config: typeof __wbg_get_deployedapp_json_config;
declare const wasm_bytes___wbg_get_deployedapp_url: typeof __wbg_get_deployedapp_url;
declare const wasm_bytes___wbg_get_deployedapp_user_yaml_config: typeof __wbg_get_deployedapp_user_yaml_config;
declare const wasm_bytes___wbg_get_deployedapp_version: typeof __wbg_get_deployedapp_version;
declare const wasm_bytes___wbg_get_deployedapp_yaml_config: typeof __wbg_get_deployedapp_yaml_config;
declare const wasm_bytes___wbg_get_instance_stderr: typeof __wbg_get_instance_stderr;
declare const wasm_bytes___wbg_get_instance_stdin: typeof __wbg_get_instance_stdin;
declare const wasm_bytes___wbg_get_instance_stdout: typeof __wbg_get_instance_stdout;
declare const wasm_bytes___wbg_get_publishpackageoutput_hash: typeof __wbg_get_publishpackageoutput_hash;
declare const wasm_bytes___wbg_get_publishpackageoutput_manifest: typeof __wbg_get_publishpackageoutput_manifest;
declare const wasm_bytes___wbg_get_user_id: typeof __wbg_get_user_id;
declare const wasm_bytes___wbg_get_user_username: typeof __wbg_get_user_username;
declare const wasm_bytes___wbg_get_userpackagedefinition_hash: typeof __wbg_get_userpackagedefinition_hash;
declare const wasm_bytes___wbg_get_wasmer_commands: typeof __wbg_get_wasmer_commands;
declare const wasm_bytes___wbg_get_wasmer_entrypoint: typeof __wbg_get_wasmer_entrypoint;
declare const wasm_bytes___wbg_get_wasmer_pkg: typeof __wbg_get_wasmer_pkg;
declare const wasm_bytes___wbg_get_wasmerpackage_data: typeof __wbg_get_wasmerpackage_data;
declare const wasm_bytes___wbg_get_wasmerpackage_manifest: typeof __wbg_get_wasmerpackage_manifest;
declare const wasm_bytes___wbg_instance_free: typeof __wbg_instance_free;
declare const wasm_bytes___wbg_intounderlyingbytesource_free: typeof __wbg_intounderlyingbytesource_free;
declare const wasm_bytes___wbg_intounderlyingsink_free: typeof __wbg_intounderlyingsink_free;
declare const wasm_bytes___wbg_intounderlyingsource_free: typeof __wbg_intounderlyingsource_free;
declare const wasm_bytes___wbg_publishpackageoutput_free: typeof __wbg_publishpackageoutput_free;
declare const wasm_bytes___wbg_readablestreamsource_free: typeof __wbg_readablestreamsource_free;
declare const wasm_bytes___wbg_runtime_free: typeof __wbg_runtime_free;
declare const wasm_bytes___wbg_set_command_name: typeof __wbg_set_command_name;
declare const wasm_bytes___wbg_set_deployedapp_app_id: typeof __wbg_set_deployedapp_app_id;
declare const wasm_bytes___wbg_set_deployedapp_config: typeof __wbg_set_deployedapp_config;
declare const wasm_bytes___wbg_set_deployedapp_created_at: typeof __wbg_set_deployedapp_created_at;
declare const wasm_bytes___wbg_set_deployedapp_description: typeof __wbg_set_deployedapp_description;
declare const wasm_bytes___wbg_set_deployedapp_id: typeof __wbg_set_deployedapp_id;
declare const wasm_bytes___wbg_set_deployedapp_json_config: typeof __wbg_set_deployedapp_json_config;
declare const wasm_bytes___wbg_set_deployedapp_url: typeof __wbg_set_deployedapp_url;
declare const wasm_bytes___wbg_set_deployedapp_user_yaml_config: typeof __wbg_set_deployedapp_user_yaml_config;
declare const wasm_bytes___wbg_set_deployedapp_version: typeof __wbg_set_deployedapp_version;
declare const wasm_bytes___wbg_set_deployedapp_yaml_config: typeof __wbg_set_deployedapp_yaml_config;
declare const wasm_bytes___wbg_set_publishpackageoutput_hash: typeof __wbg_set_publishpackageoutput_hash;
declare const wasm_bytes___wbg_set_publishpackageoutput_manifest: typeof __wbg_set_publishpackageoutput_manifest;
declare const wasm_bytes___wbg_set_user_id: typeof __wbg_set_user_id;
declare const wasm_bytes___wbg_set_user_username: typeof __wbg_set_user_username;
declare const wasm_bytes___wbg_set_userpackagedefinition_hash: typeof __wbg_set_userpackagedefinition_hash;
declare const wasm_bytes___wbg_set_wasmer_commands: typeof __wbg_set_wasmer_commands;
declare const wasm_bytes___wbg_set_wasmer_entrypoint: typeof __wbg_set_wasmer_entrypoint;
declare const wasm_bytes___wbg_set_wasmer_pkg: typeof __wbg_set_wasmer_pkg;
declare const wasm_bytes___wbg_set_wasmerpackage_data: typeof __wbg_set_wasmerpackage_data;
declare const wasm_bytes___wbg_set_wasmerpackage_manifest: typeof __wbg_set_wasmerpackage_manifest;
declare const wasm_bytes___wbg_threadpoolworker_free: typeof __wbg_threadpoolworker_free;
declare const wasm_bytes___wbg_trap_free: typeof __wbg_trap_free;
declare const wasm_bytes___wbg_user_free: typeof __wbg_user_free;
declare const wasm_bytes___wbg_userpackagedefinition_free: typeof __wbg_userpackagedefinition_free;
declare const wasm_bytes___wbg_volume_free: typeof __wbg_volume_free;
declare const wasm_bytes___wbg_wasmer_free: typeof __wbg_wasmer_free;
declare const wasm_bytes___wbg_wasmerpackage_free: typeof __wbg_wasmerpackage_free;
declare const wasm_bytes___wbg_writablestreamsink_free: typeof __wbg_writablestreamsink_free;
declare const wasm_bytes___wbindgen_exn_store: typeof __wbindgen_exn_store;
declare const wasm_bytes___wbindgen_export_5: typeof __wbindgen_export_5;
declare const wasm_bytes___wbindgen_export_6: typeof __wbindgen_export_6;
declare const wasm_bytes___wbindgen_malloc: typeof __wbindgen_malloc;
declare const wasm_bytes___wbindgen_realloc: typeof __wbindgen_realloc;
declare const wasm_bytes___wbindgen_start: typeof __wbindgen_start;
declare const wasm_bytes___wbindgen_thread_destroy: typeof __wbindgen_thread_destroy;
declare const wasm_bytes_canonical_abi_free: typeof canonical_abi_free;
declare const wasm_bytes_canonical_abi_realloc: typeof canonical_abi_realloc;
declare const wasm_bytes_closure1343_externref_shim_multivalue_shim: typeof closure1343_externref_shim_multivalue_shim;
declare const wasm_bytes_closure1345_externref_shim_multivalue_shim: typeof closure1345_externref_shim_multivalue_shim;
declare const wasm_bytes_closure191_externref_shim: typeof closure191_externref_shim;
declare const wasm_bytes_closure544_externref_shim: typeof closure544_externref_shim;
declare const wasm_bytes_closure806_externref_shim: typeof closure806_externref_shim;
declare const wasm_bytes_closure807_externref_shim: typeof closure807_externref_shim;
declare const wasm_bytes_command_binary: typeof command_binary;
declare const wasm_bytes_command_rename: typeof command_rename;
declare const wasm_bytes_command_run: typeof command_run;
declare const wasm_bytes_directory___getClassname: typeof directory___getClassname;
declare const wasm_bytes_directory_createDir: typeof directory_createDir;
declare const wasm_bytes_directory_new: typeof directory_new;
declare const wasm_bytes_directory_readDir: typeof directory_readDir;
declare const wasm_bytes_directory_readFile: typeof directory_readFile;
declare const wasm_bytes_directory_readTextFile: typeof directory_readTextFile;
declare const wasm_bytes_directory_removeDir: typeof directory_removeDir;
declare const wasm_bytes_directory_removeFile: typeof directory_removeFile;
declare const wasm_bytes_directory_writeFile: typeof directory_writeFile;
declare const wasm_bytes_initializeLogger: typeof initializeLogger;
declare const wasm_bytes_instance_wait: typeof instance_wait;
declare const wasm_bytes_intounderlyingbytesource_autoAllocateChunkSize: typeof intounderlyingbytesource_autoAllocateChunkSize;
declare const wasm_bytes_intounderlyingbytesource_cancel: typeof intounderlyingbytesource_cancel;
declare const wasm_bytes_intounderlyingbytesource_pull: typeof intounderlyingbytesource_pull;
declare const wasm_bytes_intounderlyingbytesource_start: typeof intounderlyingbytesource_start;
declare const wasm_bytes_intounderlyingbytesource_type: typeof intounderlyingbytesource_type;
declare const wasm_bytes_intounderlyingsink_abort: typeof intounderlyingsink_abort;
declare const wasm_bytes_intounderlyingsink_close: typeof intounderlyingsink_close;
declare const wasm_bytes_intounderlyingsink_write: typeof intounderlyingsink_write;
declare const wasm_bytes_intounderlyingsource_cancel: typeof intounderlyingsource_cancel;
declare const wasm_bytes_intounderlyingsource_pull: typeof intounderlyingsource_pull;
declare const wasm_bytes_memory: typeof memory;
declare const wasm_bytes_on_start: typeof on_start;
declare const wasm_bytes_readablestreamsource_cancel: typeof readablestreamsource_cancel;
declare const wasm_bytes_readablestreamsource_pull: typeof readablestreamsource_pull;
declare const wasm_bytes_readablestreamsource_type: typeof readablestreamsource_type;
declare const wasm_bytes_runWasix: typeof runWasix;
declare const wasm_bytes_runtime___getClassname: typeof runtime___getClassname;
declare const wasm_bytes_runtime_global: typeof runtime_global;
declare const wasm_bytes_runtime_js_new: typeof runtime_js_new;
declare const wasm_bytes_setSDKUrl: typeof setSDKUrl;
declare const wasm_bytes_setWorkerUrl: typeof setWorkerUrl;
declare const wasm_bytes_threadpoolworker_handle: typeof threadpoolworker_handle;
declare const wasm_bytes_threadpoolworker_new: typeof threadpoolworker_new;
declare const wasm_bytes_trap___wbg_wasmer_trap: typeof trap___wbg_wasmer_trap;
declare const wasm_bytes_userpackagedefinition___getClassname: typeof userpackagedefinition___getClassname;
declare const wasm_bytes_wasmer___getClassname: typeof wasmer___getClassname;
declare const wasm_bytes_wasmer_createPackage: typeof wasmer_createPackage;
declare const wasm_bytes_wasmer_deleteApp: typeof wasmer_deleteApp;
declare const wasm_bytes_wasmer_deployApp: typeof wasmer_deployApp;
declare const wasm_bytes_wasmer_fromFile: typeof wasmer_fromFile;
declare const wasm_bytes_wasmer_fromRegistry: typeof wasmer_fromRegistry;
declare const wasm_bytes_wasmer_fromWasm: typeof wasmer_fromWasm;
declare const wasm_bytes_wasmer_publishPackage: typeof wasmer_publishPackage;
declare const wasm_bytes_wasmer_whoami: typeof wasmer_whoami;
declare const wasm_bytes_wat2wasm: typeof wat2wasm;
declare const wasm_bytes_writablestreamsink_abort: typeof writablestreamsink_abort;
declare const wasm_bytes_writablestreamsink_close: typeof writablestreamsink_close;
declare const wasm_bytes_writablestreamsink_write: typeof writablestreamsink_write;
declare namespace wasm_bytes {
  export { wasm_bytes___externref_table_alloc as __externref_table_alloc, wasm_bytes___externref_table_dealloc as __externref_table_dealloc, wasm_bytes___wbg_atom_free as __wbg_atom_free, wasm_bytes___wbg_command_free as __wbg_command_free, wasm_bytes___wbg_deployedapp_free as __wbg_deployedapp_free, wasm_bytes___wbg_directory_free as __wbg_directory_free, wasm_bytes___wbg_get_command_name as __wbg_get_command_name, wasm_bytes___wbg_get_deployedapp_app_id as __wbg_get_deployedapp_app_id, wasm_bytes___wbg_get_deployedapp_config as __wbg_get_deployedapp_config, wasm_bytes___wbg_get_deployedapp_created_at as __wbg_get_deployedapp_created_at, wasm_bytes___wbg_get_deployedapp_description as __wbg_get_deployedapp_description, wasm_bytes___wbg_get_deployedapp_id as __wbg_get_deployedapp_id, wasm_bytes___wbg_get_deployedapp_json_config as __wbg_get_deployedapp_json_config, wasm_bytes___wbg_get_deployedapp_url as __wbg_get_deployedapp_url, wasm_bytes___wbg_get_deployedapp_user_yaml_config as __wbg_get_deployedapp_user_yaml_config, wasm_bytes___wbg_get_deployedapp_version as __wbg_get_deployedapp_version, wasm_bytes___wbg_get_deployedapp_yaml_config as __wbg_get_deployedapp_yaml_config, wasm_bytes___wbg_get_instance_stderr as __wbg_get_instance_stderr, wasm_bytes___wbg_get_instance_stdin as __wbg_get_instance_stdin, wasm_bytes___wbg_get_instance_stdout as __wbg_get_instance_stdout, wasm_bytes___wbg_get_publishpackageoutput_hash as __wbg_get_publishpackageoutput_hash, wasm_bytes___wbg_get_publishpackageoutput_manifest as __wbg_get_publishpackageoutput_manifest, wasm_bytes___wbg_get_user_id as __wbg_get_user_id, wasm_bytes___wbg_get_user_username as __wbg_get_user_username, wasm_bytes___wbg_get_userpackagedefinition_hash as __wbg_get_userpackagedefinition_hash, wasm_bytes___wbg_get_wasmer_commands as __wbg_get_wasmer_commands, wasm_bytes___wbg_get_wasmer_entrypoint as __wbg_get_wasmer_entrypoint, wasm_bytes___wbg_get_wasmer_pkg as __wbg_get_wasmer_pkg, wasm_bytes___wbg_get_wasmerpackage_data as __wbg_get_wasmerpackage_data, wasm_bytes___wbg_get_wasmerpackage_manifest as __wbg_get_wasmerpackage_manifest, wasm_bytes___wbg_instance_free as __wbg_instance_free, wasm_bytes___wbg_intounderlyingbytesource_free as __wbg_intounderlyingbytesource_free, wasm_bytes___wbg_intounderlyingsink_free as __wbg_intounderlyingsink_free, wasm_bytes___wbg_intounderlyingsource_free as __wbg_intounderlyingsource_free, wasm_bytes___wbg_publishpackageoutput_free as __wbg_publishpackageoutput_free, wasm_bytes___wbg_readablestreamsource_free as __wbg_readablestreamsource_free, wasm_bytes___wbg_runtime_free as __wbg_runtime_free, wasm_bytes___wbg_set_command_name as __wbg_set_command_name, wasm_bytes___wbg_set_deployedapp_app_id as __wbg_set_deployedapp_app_id, wasm_bytes___wbg_set_deployedapp_config as __wbg_set_deployedapp_config, wasm_bytes___wbg_set_deployedapp_created_at as __wbg_set_deployedapp_created_at, wasm_bytes___wbg_set_deployedapp_description as __wbg_set_deployedapp_description, wasm_bytes___wbg_set_deployedapp_id as __wbg_set_deployedapp_id, wasm_bytes___wbg_set_deployedapp_json_config as __wbg_set_deployedapp_json_config, wasm_bytes___wbg_set_deployedapp_url as __wbg_set_deployedapp_url, wasm_bytes___wbg_set_deployedapp_user_yaml_config as __wbg_set_deployedapp_user_yaml_config, wasm_bytes___wbg_set_deployedapp_version as __wbg_set_deployedapp_version, wasm_bytes___wbg_set_deployedapp_yaml_config as __wbg_set_deployedapp_yaml_config, wasm_bytes___wbg_set_publishpackageoutput_hash as __wbg_set_publishpackageoutput_hash, wasm_bytes___wbg_set_publishpackageoutput_manifest as __wbg_set_publishpackageoutput_manifest, wasm_bytes___wbg_set_user_id as __wbg_set_user_id, wasm_bytes___wbg_set_user_username as __wbg_set_user_username, wasm_bytes___wbg_set_userpackagedefinition_hash as __wbg_set_userpackagedefinition_hash, wasm_bytes___wbg_set_wasmer_commands as __wbg_set_wasmer_commands, wasm_bytes___wbg_set_wasmer_entrypoint as __wbg_set_wasmer_entrypoint, wasm_bytes___wbg_set_wasmer_pkg as __wbg_set_wasmer_pkg, wasm_bytes___wbg_set_wasmerpackage_data as __wbg_set_wasmerpackage_data, wasm_bytes___wbg_set_wasmerpackage_manifest as __wbg_set_wasmerpackage_manifest, wasm_bytes___wbg_threadpoolworker_free as __wbg_threadpoolworker_free, wasm_bytes___wbg_trap_free as __wbg_trap_free, wasm_bytes___wbg_user_free as __wbg_user_free, wasm_bytes___wbg_userpackagedefinition_free as __wbg_userpackagedefinition_free, wasm_bytes___wbg_volume_free as __wbg_volume_free, wasm_bytes___wbg_wasmer_free as __wbg_wasmer_free, wasm_bytes___wbg_wasmerpackage_free as __wbg_wasmerpackage_free, wasm_bytes___wbg_writablestreamsink_free as __wbg_writablestreamsink_free, wasm_bytes___wbindgen_exn_store as __wbindgen_exn_store, wasm_bytes___wbindgen_export_5 as __wbindgen_export_5, wasm_bytes___wbindgen_export_6 as __wbindgen_export_6, wasm_bytes___wbindgen_malloc as __wbindgen_malloc, wasm_bytes___wbindgen_realloc as __wbindgen_realloc, wasm_bytes___wbindgen_start as __wbindgen_start, wasm_bytes___wbindgen_thread_destroy as __wbindgen_thread_destroy, wasm_bytes_canonical_abi_free as canonical_abi_free, wasm_bytes_canonical_abi_realloc as canonical_abi_realloc, wasm_bytes_closure1343_externref_shim_multivalue_shim as closure1343_externref_shim_multivalue_shim, wasm_bytes_closure1345_externref_shim_multivalue_shim as closure1345_externref_shim_multivalue_shim, wasm_bytes_closure191_externref_shim as closure191_externref_shim, wasm_bytes_closure544_externref_shim as closure544_externref_shim, wasm_bytes_closure806_externref_shim as closure806_externref_shim, wasm_bytes_closure807_externref_shim as closure807_externref_shim, wasm_bytes_command_binary as command_binary, wasm_bytes_command_rename as command_rename, wasm_bytes_command_run as command_run, wasm_bytes_directory___getClassname as directory___getClassname, wasm_bytes_directory_createDir as directory_createDir, wasm_bytes_directory_new as directory_new, wasm_bytes_directory_readDir as directory_readDir, wasm_bytes_directory_readFile as directory_readFile, wasm_bytes_directory_readTextFile as directory_readTextFile, wasm_bytes_directory_removeDir as directory_removeDir, wasm_bytes_directory_removeFile as directory_removeFile, wasm_bytes_directory_writeFile as directory_writeFile, wasm_bytes_initializeLogger as initializeLogger, wasm_bytes_instance_wait as instance_wait, wasm_bytes_intounderlyingbytesource_autoAllocateChunkSize as intounderlyingbytesource_autoAllocateChunkSize, wasm_bytes_intounderlyingbytesource_cancel as intounderlyingbytesource_cancel, wasm_bytes_intounderlyingbytesource_pull as intounderlyingbytesource_pull, wasm_bytes_intounderlyingbytesource_start as intounderlyingbytesource_start, wasm_bytes_intounderlyingbytesource_type as intounderlyingbytesource_type, wasm_bytes_intounderlyingsink_abort as intounderlyingsink_abort, wasm_bytes_intounderlyingsink_close as intounderlyingsink_close, wasm_bytes_intounderlyingsink_write as intounderlyingsink_write, wasm_bytes_intounderlyingsource_cancel as intounderlyingsource_cancel, wasm_bytes_intounderlyingsource_pull as intounderlyingsource_pull, wasm_bytes_memory as memory, wasm_bytes_on_start as on_start, wasm_bytes_readablestreamsource_cancel as readablestreamsource_cancel, wasm_bytes_readablestreamsource_pull as readablestreamsource_pull, wasm_bytes_readablestreamsource_type as readablestreamsource_type, wasm_bytes_runWasix as runWasix, wasm_bytes_runtime___getClassname as runtime___getClassname, wasm_bytes_runtime_global as runtime_global, wasm_bytes_runtime_js_new as runtime_js_new, wasm_bytes_setSDKUrl as setSDKUrl, wasm_bytes_setWorkerUrl as setWorkerUrl, wasm_bytes_threadpoolworker_handle as threadpoolworker_handle, wasm_bytes_threadpoolworker_new as threadpoolworker_new, wasm_bytes_trap___wbg_wasmer_trap as trap___wbg_wasmer_trap, wasm_bytes_userpackagedefinition___getClassname as userpackagedefinition___getClassname, wasm_bytes_wasmer___getClassname as wasmer___getClassname, wasm_bytes_wasmer_createPackage as wasmer_createPackage, wasm_bytes_wasmer_deleteApp as wasmer_deleteApp, wasm_bytes_wasmer_deployApp as wasmer_deployApp, wasm_bytes_wasmer_fromFile as wasmer_fromFile, wasm_bytes_wasmer_fromRegistry as wasmer_fromRegistry, wasm_bytes_wasmer_fromWasm as wasmer_fromWasm, wasm_bytes_wasmer_publishPackage as wasmer_publishPackage, wasm_bytes_wasmer_whoami as wasmer_whoami, wasm_bytes_wat2wasm as wat2wasm, wasm_bytes_writablestreamsink_abort as writablestreamsink_abort, wasm_bytes_writablestreamsink_close as writablestreamsink_close, wasm_bytes_writablestreamsink_write as writablestreamsink_write };
}

declare const getWasm: () => typeof wasm_bytes;

export { getWasm };
